services:
  server:
    image: mitmproxy/mitmproxy:${image_ver:-12}
    hostname: mitmproxy-server
    pull_policy: always
    restart: unless-stopped
    command: 
      - mitmweb
      - --no-web-open-browser
      - --web-host
      - 0.0.0.0
      - --set
      - web_password=${web_password}
    init: true
    ports:
      - 5080:8080
      - 5081:8081
      - 6080:38080
      - 6081:38081
    extra_hosts:
      - host.docker.internal:host-gateway
