services:
  server:
    image: gvenzl/oracle-free:${image_ver:-slim}
    hostname: oracle
    pull_policy: always
    restart: unless-stopped
    init: true
    environment:
      - ORACLE_DATABASE=${ORACLE_DATABASE:-}
      - ORACLE_PASSWORD=${ORACLE_PASSWORD:-oracle}
      - APP_USER=${APP_USER:-app}
      - APP_USER_PASSWORD=${APP_USER_PASSWORD:-app}
    volumes:
      - ${SCRIPTS_DIR:-./scripts}:/opt/oracle/scripts
      - data:/opt/oracle/oradata
    ports:
      - 1521:1521
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
volumes:
  data:
