services:
  sd-webui:
    image: jianshao/sd-webui-rt:${image_tag}
    container_name: sd-webui-server
    command:
      - python
      - launch.py 
      - --xformers
      - --listen
    # network_mode: host
    restart: unless-stopped
    environment:
      - https_proxy=${https_proxy:-}
      - HF_HUB_ENABLE_HF_TRANSFER=${HF_HUB_ENABLE_HF_TRANSFER:-0}
    volumes:
      - ~/.ssh:/home/devel/.ssh
      - ~/.ifnude:/home/devel/.ifnude
      - ${model_cache_path:-~/.cache}:/home/devel/.cache
      - ./install-models.sh:/home/devel/.local/bin/install-models.sh
      - ${sd_webui_root}:/home/devel/stable-diffusion-webui
    ports:
      - 7860:7860
