#!/bin/bash
docker run --rm -it --network host \
       -v ~/.ollama:/home/ubuntu/.ollama \
       -v ~/.local:/home/ubuntu/.local \
       -v ~/.cache:/home/ubuntu/.cache \
       -v ~/.config:/home/ubuntu/.config \
       -v ~/.nvm:/home/ubuntu/.nvm \
       -v ~/.copilot:/home/ubuntu/.copilot \
       -v ~/.opencode:/home/ubuntu/.opencode \
       jianshao/ollama ollama $*