services:
  server:
    image: jianshao/ollama:${ollama_image_tag}
    hostname: ollama-server
    pull_policy: always
    restart: unless-stopped
    working_dir: /home/ubuntu/workspace
    init: true
    volumes:
      - ${workspace:-~/workspace}:/home/ubuntu/workspace
      - ~/.ollama:/home/ubuntu/.ollama
    environment:
      - https_proxy=${https_proxy:-}
      - OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION:-1}
    ports:
      - 11434:11434
