services:
  server:
    image: jianshao/ollama:${ollama_image_tag-latest}
    hostname: ollama-server
    pull_policy: always
    restart: unless-stopped
    init: true
    volumes:
      - ~/.ollama:/home/ubuntu/.ollama
      - ~/.local:/home/ubuntu/.local
      - ~/.cache:/home/ubuntu/.cache
      - ~/.config:/home/ubuntu/.config
      - ~/.nvm:/home/ubuntu/.nvm
      - ~/.copilot:/home/ubuntu/.copilot
      - ~/.opencode:/home/ubuntu/.opencode
    environment:
      - https_proxy
      - http_proxy
      - no_proxy
      - OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION:-1}
      - OLLAMA_VULKAN=${OLLAMA_VULKAN:-0}
    ports:
      - 11434:11434
