#!/bin/bash
docker run --rm -it --network=container:ollama-server-1 \
           -v ~/.ollama_openclaw:/home/devel/.openclaw \
           -v ~/.ollama:/home/devel/.ollama \
           -v ~/.nvm:/home/devel/.nvm \
           jianshao/sandbox-base openclaw $*