apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: searxng
          image: docker.io/searxng/searxng:latest
          envFrom:
          - configMapRef:
              name: env-cm
              optional: true
          volumeMounts:
            - mountPath: /etc/searxng
              name: searxng-config
          ports:
            - containerPort: 8080
          securityContext:
            capabilities:
              drop: ["ALL"]
              add: ["CHOWN", "SETGID", "SETUID"]
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      restartPolicy: Always
      volumes:
        - name: searxng-config
          hostPath:
            path: /usr/local/etc/searxng
            type: Directory
