apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: searxng
  name: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
        - name: searxng
          image: docker.io/searxng/searxng:latest
          env:
            - name: SEARXNG_BASE_URL
              value: "https://${SEARXNG_HOSTNAME:-localhost}/"
            - name: UWSGI_WORKERS
              value: "${SEARXNG_UWSGI_WORKERS:-4}"
            - name: UWSGI_THREADS
              value: "${SEARXNG_UWSGI_THREADS:-4}"
          volumeMounts:
            - mountPath: /etc/searxng
              name: searxng-config
          ports:
            - containerPort: 8080
          securityContext:
            capabilities:
              drop: ["ALL"]
              add: ["CHOWN", "SETGID", "SETUID"]
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
      restartPolicy: Always
      volumes:
        - name: searxng-config
          hostPath:
            path: ./searxng
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  namespace: searxng
  name: searxng
spec:
  type: ClusterIP
  selector:
    app: searxng
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
